[package]
name = "tidal-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tao = "0.34.5"
tokio = { version = "1.49.0", features = ["full"] }
wry = "0.54.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libmpv2 = "5.0.3"
